export const LEAVE_GROUP_DELAY = 100

export const LEAVE_OVERLAP_THRESHOLD = 0.5

export const Z_INDEX = {
  CONTAINER: 0,
  DEVICE: 10,
  SELECTED: 999,
  DRAGGING: 1000
}

export const DRAG_THROTTLE_DELAY = 16

export const ANIMATION_DURATION = 200
